#1
SELECT ENAME, SAL FROM EMP WHERE SAL < ALL (SELECT SAL FROM EMP WHERE EMPNO=7566);

#2
SELECT EMPNO, ENAME FROM EMP WHERE SAL > ALL (SELECT AVG(SAL) FROM EMP);

#3
SELECT ENAME FROM EMP WHERE JOB='MANAGER';

#4
SELECT ENAME, SAL FROM EMP WHERE SAL > ALL (SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO);

#5
SELECT ENAME, JOB from EMP WHERE JOB != 'CLERK' AND SAL < ANY (SELECT SAL FROM EMP WHERE JOB = 'CLERK');

#6
INSERT INTO DEPT VALUES (50, 'SOFTWARE', 'NEW YORK');

#7
INSERT INTO EMP(ENAME, EMPNO, HIREDATE) VALUES ('EMPLOYEE1', 1234, CURRENT_DATE());

#8
INSERT INTO BONUS VALUES ('ALLEN', 'SALESMAN', '1600.00', '300.00');
INSERT INTO BONUS VALUES ('WARD', 'SALESMAN', '1250.00', '500.00');
INSERT INTO BONUS VALUES ('MARTIN', 'SALESMAN', '1250.00', '1400.00');
INSERT INTO BONUS VALUES ('TURNER', 'SALESMAN', '1500.00', '0.00');

#9
UPDATE DEPT SET LOC = 'IZMIR' WHERE DNAME = 'SOFTWARE'

#10
UPDATE EMP SET SAL = SAL + SAL * 10/100;

#11
DELETE FROM EMP where EMPNO = 1234;

#12
DELETE d FROM DEPT AS d WHERE d.DEPTNO IN (SELECT DEPTNO FROM (SELECT sd.DEPTNO FROM DEPT sd LEFT JOIN EMP se ON sd.DEPTNO = se.DEPTNO WHERE se.EMPNO IS NULL) AS ssd);