#1
select DEPTNO, AVG(SAL) from EMP GROUP BY DEPTNO;

#2
select JOB, SUM(SAL), SUM(COMM) from EMP GROUP BY JOB;

#3
select JOB, SUM(SAL) as TOT_SAL from EMP GROUP BY JOB HAVING TOT_SAL > 5000;

#4
elect DEPTNO, COUNT(EMPNO) as EMP_COUNT from EMP GROUP BY DEPTNO HAVING EMP_COUNT > 3;

#5
select DEPTNO, AVG(SAL) AVG_SAL from EMP GROUP BY DEPTNO HAVING AVG_SAL > 2000;

#6
select DEPTNO, JOB, SUM(SAL) TOT_SAL, COUNT(EMPNO) EMP_COUNT FROM EMP GROUP BY DEPTNO, JOB;

#7
select DEPTNO, JOB, MIN(SAL) MIN_SAL, MAX(SAL) MAX_SAL from EMP GROUP BY DEPTNO, JOB HAVING MAX_SAL > 2500;

#8
select DEPTNO, COUNT(EMPNO) EMP_COUNT from EMP WHERE SAL > 1500 GROUP BY DEPTNO;

#9
select DNAME DEPTNAME, COUNT(EMPNO) EMP_COUNT from EMP e INNER JOIN DEPT d on e.DEPTNO=d.DEPTNO GROUP BY DNAME;

#10
select d.DEPTNO, MAX(e.SAL) HIGHEST_SALARY from (select dd.DEPTNO from DEPT dd where dd.LOC = "NEW YORK") d inner join EMP e on d.DEPTNO=e.DEPTNO GROUP BY d.DEPTNO;