#1
CREATE VIEW HighSal AS SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL > 2000;

#2
INSERT INTO HighSal VALUES(1234, 'Employee1', 5000);

#3
select * from HighSal;

#4
select EMPNO, ENAME, SAL from EMP where SAL > 2000;

#5
CREATE VIEW DeptSal AS SELECT d.DEPTNO, SUM(SAL) SAL FROM DEPT d INNER JOIN EMP e ON d.DEPTNO = e.DEPTNO GROUP BY d.DEPTNO;

#6
select * from DeptSal where SAL > 9000;

#7
CREATE TABLE LOGEMP(EMPNO DECIMAL(4, 0), ENAME VARCHAR(10), LOGDATE DATE, LOGTYPE VARCHAR(10));

#8
CREATE TRIGGER INSERTLOGEMP AFTER INSERT on EMP FOR EACH ROW INSERT INTO LOGEMP VALUES (new.EMPNO, new.ENAME, CURRENT_DATE(), "insert");

#9
CREATE TRIGGER DELETELOGEMP AFTER DELETE on EMP FOR EACH ROW INSERT INTO LOGEMP VALUES (old.EMPNO, old.ENAME, CURRENT_DATE(), "delete");

#10
CREATE TRIGGER UPDATELOGEMP AFTER UPDATE on EMP FOR EACH ROW INSERT INTO LOGEMP VALUES (new.EMPNO, new.ENAME, CURRENT_DATE(), "update");